// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADsKzP4C5YPM0k9gesMZDkQq_3A0c_jAo',
    appId: '1:946084676492:web:8b9f4aa121b3ad28df8ca9',
    messagingSenderId: '946084676492',
    projectId: 'instagram-clone-54971',
    authDomain: 'instagram-clone-54971.firebaseapp.com',
    storageBucket: 'instagram-clone-54971.appspot.com',
    measurementId: 'G-ZJ392KXR4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA6AUK-eqxyFGHpmEvpvdDmKPSyILMMDk',
    appId: '1:946084676492:android:f2322cf436ce3725df8ca9',
    messagingSenderId: '946084676492',
    projectId: 'instagram-clone-54971',
    storageBucket: 'instagram-clone-54971.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9DzJKrpyTF6uoDZ6G8xabsIENHDji4g4',
    appId: '1:946084676492:ios:8c29d622dc0fd083df8ca9',
    messagingSenderId: '946084676492',
    projectId: 'instagram-clone-54971',
    storageBucket: 'instagram-clone-54971.appspot.com',
    iosClientId: '946084676492-gorh1hgjjkcjr8c1g5bbtq6l1ave0b3n.apps.googleusercontent.com',
    iosBundleId: 'com.AndyAn.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9DzJKrpyTF6uoDZ6G8xabsIENHDji4g4',
    appId: '1:946084676492:ios:54bcffcfb4de55c1df8ca9',
    messagingSenderId: '946084676492',
    projectId: 'instagram-clone-54971',
    storageBucket: 'instagram-clone-54971.appspot.com',
    iosClientId: '946084676492-rbvugot2gmhmtb26ucrlov4p0akth78l.apps.googleusercontent.com',
    iosBundleId: 'com.AndyAn.instagramClone.RunnerTests',
  );
}
